logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

  loggers:
    food_review_api:
      level: DEBUG
      handlers: [console]
      propagate: no
    # uvicorn:
    #   level: DEBUG
    #   handlers: [console]
    #   propagate: no

  root:
    level: INFO
    handlers: [console]

database:
  filename: data/reviews_1.csv
